In [33]:
import sys
sys.path.append('C:/Users/Lenovo/Desktop/2024_E/tools/')
from CM_dataset import CM_dataset
from load_array import LoadArray
from mxnet import autograd,gluon,init
from animator import Animator
from mxnet import np, npx
npx.set_np()
model = gluon.nn.Sequential()
model.add(

    # gluon.nn.Dense(64, activation='relu'),
    gluon.nn.Dense(5),
    gluon.nn.Dense(1)

)
model.initialize(init.Normal(sigma=0.01))
model.load_parameters(r'C:/Users/Lenovo/Desktop/2024_E/model_params/model_params.params')
model(np.array([[126.79,	60.48,	441











]]))

array([[235.88425]])

In [34]:
model[0].weight.data()

array([[-0.9108732 ,  1.2576402 , -0.00164445],
       [-0.93235683,  1.2403162 ,  0.01654914],
       [ 0.9402324 , -1.2607988 , -0.01953712],
       [ 0.93269867, -1.260071  , -0.00180963],
       [ 0.88542783, -1.2886182 ,  0.00320756]])

model[1].weight.data()

In [36]:
model[1].weight.data()

array([[-1.2883068, -1.4471098,  1.529142 ,  1.3148528,  1.3657652]])

In [37]:
model[0].bias.data()

array([ 3.0220165,  3.0095584, -3.0248015, -3.0072885, -3.0651994])

In [38]:
model[1].bias.data()

array([-2.3515937])